name: Download file from wallhaven

# Controls when the workflow will run
on:
  schedule:
    # Run at 6am everyweek
    - cron: "0 6 * * 0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup python
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.0

      # Install python dependencies
      - name: Install dependencies
        run: pip install requests

      # Run python script
      - name: Download weekly wallpaper
        run: python imageofday.py
      - name: Install imagemagick
        run: sudo apt update && sudo apt install -y imagemagick
      - name: Convert png to jxl
        run: convert docs/images/background/image9.png docs/images/background/image9.jxl
      - name: Delete png file
        run: rm docs/images/background/image9.png

      - name: Commit files
        run: |
          git pull
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "Weekly wallpaper" -a || true
      - name: Push image
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
